[package]
name = "sharez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.8.6"
chrono = "0.4"
tokio = { version = "1.28", features = ["full"] }
image = "0.24"
minifb = "0.25.0"